#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('lib', __dir__))

require 'thor'
require 'dotenv/load'

#
# Example usage:
#
#     smarthr-api-cli crew dump
#
#
class App < Thor
  # Load all the clis and register them as subcommands
  Dir.glob('./lib/clis/*.rb').each do |file|
    require file
  end

  Clis.constants.each do |const|
    desc const.downcase, "#{const} clis"
    subcommand const.downcase, Clis.const_get(const)
  end
end

Dotenv.load
App.start(ARGV)
